# Generated by Django 5.1.2 on 2024-10-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE')], max_length=50)),
                ('user', models.CharField(max_length=40, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CheckList.checklistitem')),
            ],
        ),
    ]
