# Generated by Django 5.1.3 on 2024-11-14 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0002_checklistitemstatus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistcategory',
            name='items',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CheckList.checklistcategory'),
            preserve_default=False,
        ),
    ]
