# Generated by Django 5.1.2 on 2024-10-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0002_checklistitemstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='titles',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='Notes',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='notes',
            field=models.TextField(default='Deafult Text', max_length=500),
            preserve_default=False,
        ),
    ]
