# Generated by Django 5.1.2 on 2024-10-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0003_rename_titles_checklistitem_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='cardinality',
            field=models.IntegerField(unique=True),
        ),
    ]
