# Generated by Django 5.1.2 on 2024-10-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0004_alter_checklistitem_cardinality'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='titles',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
