# Generated by Django 5.1.2 on 2024-10-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0005_checklistitem_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='titles',
        ),
    ]
