# Generated by Django 5.1.2 on 2024-10-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0006_remove_checklistitem_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemstatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE')], default='PENDING', max_length=50),
        ),
    ]
