# Generated by Django 5.0.9 on 2024-10-31 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0008_cataloguedata_cataloguesubtype_cataloguetype_doctype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistcategory',
            name='items',
            field=models.ManyToManyField(related_name='categories', to='CheckList.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='users',
            field=models.ManyToManyField(related_name='checklist_items', through='CheckList.CheckListItemStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklistitemstatus',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CheckList.checklistitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklistitemstatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
