# Generated by Django 5.0.9 on 2024-10-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0009_checklistcategory_items_checklistitem_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='doc_type',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
        migrations.DeleteModel(
            name='DocType',
        ),
    ]
