# Generated by Django 5.1.1 on 2024-10-23 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0010_personalinfotype_userpersonalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCatalogSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCatalogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpersonalinfo',
            name='info_type',
        ),
        migrations.RemoveField(
            model_name='userpersonalinfo',
            name='user',
        ),
        migrations.CreateModel(
            name='ClientCatalogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckList.clientcatalogsubtype')),
            ],
        ),
        migrations.AddField(
            model_name='clientcatalogsubtype',
            name='catalog_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckList.clientcatalogtype'),
        ),
        migrations.DeleteModel(
            name='PersonalInfoType',
        ),
        migrations.DeleteModel(
            name='UserPersonalInfo',
        ),
    ]
