# Generated by Django 5.1.1 on 2024-10-23 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckList', '0011_clientcatalogsubtype_clientcatalogtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorDutySubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutorDutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutorDutyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckList.executordutysubtype')),
            ],
        ),
        migrations.AddField(
            model_name='executordutysubtype',
            name='duty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckList.executordutytype'),
        ),
    ]
