# Generated by Django 5.0.9 on 2024-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('contact', models.TextField(max_length=100)),
                ('company_name', models.TextField(max_length=100)),
                ('user', models.TextField(max_length=50)),
                ('type', models.ManyToManyField(to='ContactManager.contacttype')),
            ],
        ),
    ]
