# Generated by Django 5.1.3 on 2024-11-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
