# Generated by Django 5.1.3 on 2024-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EXECUTOR', 'Executor'), ('CLIENT', 'Client'), ('GUEST', 'Guest'), ('CUSTOMER', 'Customer')], default='GUEST', max_length=10),
        ),
    ]
