# Generated by Django 5.1.3 on 2024-11-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_alter_customer_user_alter_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='assinged_customer',
            field=models.ManyToManyField(blank=True, null=True, to='UserManagement.customer'),
        ),
    ]
