# Generated by Django 5.1.3 on 2024-11-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_alter_staff_assinged_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='citizenship',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='father_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='mother_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='pervious_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='sex',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
