# Generated by Django 5.1.3 on 2024-11-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_personalinformation_citizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
