# Generated by Django 5.1.3 on 2024-11-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_personalinformation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='province',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='street_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
