# Generated by Django 5.1.3 on 2024-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(default='baseimg/logo.png', upload_to='baseimgs')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
