# Generated by Django 5.1.2 on 2024-10-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='title',
            field=models.CharField(default='demo title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='title',
            field=models.CharField(default='demo title', max_length=100),
            preserve_default=False,
        ),
    ]
