# Generated by Django 5.1.3 on 2024-11-12 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='url',
        ),
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
