# Generated by Django 5.1.3 on 2024-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
