# Generated by Django 5.0.9 on 2024-11-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManager', '0002_alter_asset_user_alter_debt_user'),
        ('AssetManager', '0002_remove_doc_url_doc_file'),
    ]

    operations = [
    ]
