# Generated by Django 5.1.2 on 2024-10-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManager', '0002_asset_title_debt_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
