# Generated by Django 5.1.2 on 2024-11-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManager', '0004_doctype_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc',
        ),
        migrations.DeleteModel(
            name='DocType',
        ),
    ]
